config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    resources :comments
  end

  resources :comments do
    resources :comments 
  end
  
  root 'pages#home'

  scope :pages, controller: :pages do
    get 'about'
    get 'portfolio'
    get 'contacts'
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user

  belongs_to :commentable, polymorphic: true
  has_many :comments, :as => :commentable
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, as: :commentable
  belongs_to :user
  
  def post
    commentable.is_a?(Post) ? commentable : commentable.post
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX},
            uniqueness: { case_sensitive: false }
  has_secure_password          
  validates :password, length: { minimum: 6 }
  
  has_many :posts
  has_many :comments
  
  mount_uploader :avatar, AvatarUploader
            
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :get_parent
  before_action :comment_find, only: [:edit, :update, :destroy]

  def new
    @comment = @parent.comments.build
  end
 
  def edit

  end


  def create
    @comment = @parent.comments.build(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to posts_path(@comment), :notice => 'Thank you for your comment!'
    else
      render :new
    end
  end


  def update

    @comment.update(params[:comment].permit(:content))
    
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to posts_path, notice: 'Комментарий обновлен.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy

    @comment.destroy
    redirect_to posts_path
  end
 
  private

  def comment_params
    params.require(:comment).permit(:body, :title, :user_id, :commentable_id, :commentable_type)
  end

  def comment_find
    @comment = Comment.find(params[:id])
  end
   
  def get_parent
    @parent = Post.find_by_id(params[:post_id]) if params[:post_id]
    @parent = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
     
    redirect_to root_path unless defined?(@parent)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: [:show, :edit, :update, :destroy]
  
  def index
    @posts = Post.all.order('created_at DESC') 
    unless signed_in?
      redirect_to signin_url
    end
  end
 
  def show
  end
 
  def new
    @post = Post.new
  end
   
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to posts_path, :notice => "Your post was created successfully."
    else
      render :action => :new
    end
  end

  def update
    @post.update_attributes (post_params)

    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Пост обновлен.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @post.destroy
    redirect_to @post
  end

private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  user = User.find_by(email: params[:session][:email].downcase)
  if user && user.authenticate(params[:session][:password])
    sign_in user
    redirect_to posts_path
  else
    flash[:error] = 'Invalid email/password combination' # Not quite right!
    render 'new'
  end
end

  def destroy
    sign_out
    redirect_to posts_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  before_action :user_find,      only: [:edit, :update, :show]


  def show
  end

  def new
    @user = User.new
  end 

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      redirect_to posts_url #goes to the new users show profile page
    else
      render 'new'
    end
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to posts_url
    else
      render 'edit'
    end
  end


  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)                           
    end

    def user_find
      @user = User.find(params[:id])
    end

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end
  
   def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

   def current_user?(user)
    user == current_user
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

   def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def avatar_for(user, options = { size:80 })
    size = options[:size]
   if user.avatar?
    image_tag user.avatar.url(:thumb), width: size
   else
    image_tag "user.png", width: size
  end
end
end

app/views/comments/_comment.html.erb
 <%= image_tag comment.user.avatar.url, width: 50 %>
 <%= User.find(comment.user_id).email %> 

<li class="comment">
  <h3><%= comment.title %></h3>

  <div class="body">
    <%= comment.body %>
  </div>

  <% if comment.user_id == current_user.id %>
  <%= link_to "Удалить", post_comment_path(@post, comment), :method => :delete, data: { confirm: 'Are you sure?' } %>
  <%= link_to 'Редактировать', edit_post_comment_path(@post, comment) %> 
  <% end %>   
  <%= link_to 'Add a Reply', new_comment_comment_path(comment) %>


  <% unless comment.comments.empty? %>
    <ul class="comment_list">
      <%= render :partial => 'comments/comment', :collection => comment.comments %>
    </ul>
  <% end %>
</li>

app/views/comments/edit.html.erb
<div class= "container" %>
<%= form_for [@parent, @comment] do |f| %>
	<%= f.text_area :title %>
	<%= f.text_area :body %>
	<%= f.submit %>
<% end %>
</div>

app/views/comments/new.html.erb
<div class= "container" %>
<%= form_for [@parent, @comment] do |f| %>
	<%= f.text_area :title %>
	<%= f.text_area :body %>
	<%= f.submit %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Testapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<%= render 'shared/header' %>
<div class="container">
  <div class='page frontpage'>
        <div class='pure-g'>
          <div class='pure-u-1 pure-u-lg-10-24'>
            <div class='pure-container'>
              <h1>Batrakov Dmitry</h1>
              <p class='shortInfo'>
                programmer: Ruby(Ruby on Rails)
                </br>
                </br>
              </p>
              <table class='sitesAndContacts'>
                <tr>
                  <th>
                    <%= image_tag("email_ico.png", :alt => "rss feed") %>
                    email: basher9696@gmail.com
                  </th>
                </tr>
               <tr>
                  <th>
                  </br>
                    <%= image_tag("github_ico.png", :alt => "rss feed") %>
                    github: https://github.com/Dmitry96/
                  </th>
                </tr>
                <tr>
                  <th>
                  </br>
                    <%= image_tag("skype.png", :alt => "rss feed") %>
                    skype: strikerst3am
                  </th>
                </tr>

              </table>
            </div>
          </div>
        </div>
      </div>
      </div>

<%= render 'shared/footer' %>

app/views/pages/home.html.erb
<div class="test"> 

	 <header class="site-header navbar-fullwidth navbar-transparent overlay-black">
  <!-- Top navbar & branding -->
  <nav class="navbar navbar gl-header-main-menu ">
    <div class="container">

      <!-- Toggle buttons and brand -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar" aria-expanded="true" aria-controls="navbar">
          <span class="glyphicon glyphicon-option-vertical"></span>
        </button>
      </div>
      <!-- END Toggle buttons and brand -->


      <div id="navbar" class="navbar-collapse collapse" >
        <ul class="nav navbar-nav">
        	<li style="font-family: 'FuturaPTWeb-Book'; font-size: 40px;"> <%= link_to "BATRAKOFF.INFO", root_path, {style: "color: black"} %></li>
        </ul>


          <ul class="nav navbar-nav navbar-right">
          	<li style="font-family: 'FuturaPTWeb-Book';font-size: 18px;""><%= link_to "Блог", posts_path, {style: "color: black"} %></li>
          	<li style="font-family: 'FuturaPTWeb-Book';font-size: 18px;""><%= link_to "Обо мне", about_path, {style: "color: black"} %></li>
          </ul>

      </div>

      <!-- END Top navbar -->
    </div>
  </nav>
</header>

	        <!-- Banner -->
        <div class=" banner banner-lg text-white text-center overlay-black">
          <div class="container">
            <h1 style="font-size: 60px; font-family: 'FuturaPTWeb-Book'; margin-top: 200px;">Батраков Дмитрий </br> Веб Разработчик</h1>
                <a href="#" class="btn btn-success">Написать мне</a>
      </div>
    </div>

</div>
	

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>

<%= f.label :title, "Название поста" %>
<br>
<%= f.text_field :title, class: "form-control" %>
<br>
<%= f.text_area :body, class: "form-control insert-post-here", rows: 17 %>
<br>
<%= f.submit "Опубликовать", class: "btn btn-success" %>

<% end %>

app/views/posts/edit.html.erb
<%= render 'shared/header' %>
<div class="container">
<h4> Edit Post</h4>
<%= render 'form' %>
<%= link_to 'Show', @post %> |
<%= link_to 'Back', post_path %>
</div>
<%= render 'shared/footer' %>

app/views/posts/index.html.erb
<%=  render 'shared/header' %>
	<div class="container">
		<% @posts.each do |post| %>
		  <article class="row">
            <aside class="col-lg-2.post-meta">
                <div class="col-lg-10">
                    <div class="avatar">   
                        <%= image_tag post.user.avatar.url, width: 50 %>
                        <%= post.user.name %>
                    </div> 
                    <h2><%= link_to post.title, post %></h2>
                    <div class="text-right">
                    <% if post.user_id == current_user.id %>
    			    <%= link_to 'Редактировать', edit_post_path(post) %> 
                    <%= link_to 'Удалить', post, method: :delete, data: { confirm: 'Are you sure?' } %> 
    	            <% end %>
    	            </div>
                </div>  
            </aside>      
		  </article>
        <% end %> 
	</div>	
<%=  render 'shared/footer' %>

app/views/posts/new.html.erb
<%= render 'shared/header' %>
	<div class="container">
			<%= render 'form' %>
		<%= link_to "Back", posts_path %>
	</div>
<%= render 'shared/footer' %>	

app/views/posts/show.html.erb
<div class="container">

<h1><%= @post.title %></h1>
 
<div class="body">
  <%= @post.body %>  
</div>
 
<h2>Comments</h2>
 
<p><%= link_to 'Add a Comment', new_post_comment_path(@post) %></p>
 
<ul class="comment_list">
  <%= render :partial => 'comments/comment', :collection => @post.comments %>
</ul>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
    <p>Copyright © Batrakoff.Info 2016 All Rights Reserved</p>
  <nav>
  </nav>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <ul class="nav navbar-nav">
      <li style="font-family: 'FuturaPTWeb-Book'; font-size: 28px;"> <%= link_to "Batrakoff.Info", root_path, {style: "color: white"} %></li>
      </ul>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
       <li style="font-family: 'FuturaPTWeb-Book';font-size: 18px;""><%= link_to "Обо мне", about_path, {style: "color: white"} %></li>
       <li style="font-family: 'FuturaPTWeb-Book';font-size: 18px;""><%= link_to "Блог", posts_path, {style: "color: white"} %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <% if signed_in? %>
        <li id="fat-menu" class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
          </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to 'Новая запись', new_post_path %></li>
              <li>
                <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to signin_path do %>
              <span class="glyphicon glyphicon-log-in"> </span>
            <% end %> 
            </li> 

            <li><%= link_to signup_path do %>
              <span class="glyphicon glyphicon-user"> </span>
            <% end %> 
            </li> 
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/users/_form.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user, html: {multipart: true}) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.file_field :avatar %>
      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<%=  render 'shared/header' %>
<div class="container">
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user , html: {multipart: true}) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= image_tag @user.avatar_url(:thumb) if @user.avatar? %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.file_field :avatar %>
      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>
</div>
<%=  render 'shared/footer' %>

app/views/users/new.html.erb
<%= render 'shared/header' %>
	<div class="container">
			<%= render 'form' %>
		<%= link_to "Back", posts_path %>
	</div>
<%= render 'shared/footer' %>	

app/views/users/show.html.erb
<div class="avatar">
<%= avatar_for(@user) %>
</div>
<%= @user.name %>, <%= @user.email %>